'use strict';
const $=id=>document.getElementById(id),C=$('preview'),ctx=C.getContext('2d'),L='#c3ff55',FG='#e9edf2',M='#83909d',R='#f27b83';
const defaults={error_code:'CS1002',message:'; expected',filename:'Player.cs',before:['void Start()','{','    Debug.Log("Hello")','}'],after:['void Start()','{','    Debug.Log("Hello");','}'],bug:'../assets/CS1002.png'};
let bugData=STUDIO_ASSETS.CS1002,bug,hosts=[],time=4.4,playing=false,last=0,model,ready=false,activeJob=false;
const font=(n,mono=false)=>{ctx.font=`${n}px ${mono?'ArchiveMono':'ArchiveSans'}`;};
const width=(s,n,mono=true)=>{font(n,mono);return ctx.measureText(s).width;};
function tx(s,x,cy,n=32,color=FG,mono=false,align='left'){font(n,mono);ctx.fillStyle=color;ctx.textAlign=align;ctx.textBaseline='alphabetic';const m=ctx.measureText(s);ctx.fillText(s,x,cy+(m.actualBoundingBoxAscent-m.actualBoundingBoxDescent)/2);}
function rr(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill){ctx.fillStyle=fill;ctx.fill();}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=2;ctx.stroke();}}
function line(points,color,w=1){ctx.beginPath();ctx.moveTo(...points[0]);for(const p of points.slice(1))ctx.lineTo(...p);ctx.strokeStyle=color;ctx.lineWidth=w;ctx.stroke();}
function circle(x,y,r,color,stroke){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);if(color){ctx.fillStyle=color;ctx.fill();}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=1;ctx.stroke();}}
function glow(x,y,r=70){const g=ctx.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,'#b7ff5535');g.addColorStop(1,'#b7ff5500');ctx.fillStyle=g;ctx.fillRect(x-r,y-r,r*2,r*2);}
const ease=p=>{p=Math.max(0,Math.min(1,p));return p*p*(3-2*p);};
const bez=(a,b,c,d,p)=>[0,1].map(i=>(1-p)**3*a[i]+3*(1-p)**2*p*b[i]+3*(1-p)*p*p*c[i]+p**3*d[i]);
function loadImage(src){return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(Error('Could not load image.'));im.src=src;});}
function message(s,x,y,maxsize,maxw,align='left',color=FG){let lines=[],size=maxsize;for(;size>=23;size--){lines=[];let str='';for(const word of s.split(/\s+/)){const z=(str+' '+word).trim();if(width(z,size)<=maxw)str=z;else{if(str)lines.push(str);str=word;}}if(str)lines.push(str);if(lines.length<=2&&lines.every(z=>width(z,size)<=maxw))break;}if(size<23)throw Error('Compiler message is too long for the two-line area.');lines.forEach((z,i)=>tx(z,x,y+(i-(lines.length-1)/2)*(size+7),size,color,true,align));}
function cfg(){const out={error_code:$('errorcode').value.trim(),filename:$('filename').value.trim()||'Player.cs',message:$('message').value,before:$('before').value.replace(/\t/g,'    ').split('\n'),after:$('after').value.replace(/\t/g,'    ').split('\n'),bug:'embedded.png',bug_data_url:bugData};if($('focus').value)out.focus_line=Number($('focus').value);return out;}
function build(){const q=cfg();if(!/^CS\d{4}$/.test(q.error_code))throw Error('Use an error code such as CS1002.');if(!q.message.trim()||q.message.includes('\n'))throw Error('Enter a compiler message.');const count=Math.max(q.before.length,q.after.length);if(count>200)throw Error('Up to 200 source lines are supported.');let changes=[];for(let row=0;row<count;row++){const a=q.before[row]||'',b=q.after[row]||'';if(a===b)continue;let p=0;while(p<Math.min(a.length,b.length)&&a[p]===b[p])p++;let ae=a.length,be=b.length;while(ae>p&&be>p&&a[ae-1]===b[be-1]){ae--;be--;}changes.push({row,start:p,oldend:ae,end:be});}if(!changes.length)throw Error('Before and After must contain a correction.');const focus=changes.find(c=>c.row===q.focus_line-1)||changes[0],visible=Math.min(count,28),start=Math.max(0,Math.min(count-visible,focus.row-Math.floor(visible/2))),end=start+visible;let size=40;for(;size>=26;size--){if([...q.before.slice(start,end),...q.after.slice(start,end)].every(s=>width(s,size)<=704))break;}if(size<26)throw Error('A visible code line is too wide. Shorten that line.');size=Math.min(size,Math.floor(980/visible)-5);const step=Math.min(58,size+9),bottom=Math.max(690,350+(visible-1)*step+54);const target=[Math.min(922,220+width((q.after[focus.row]||'').slice(0,focus.start),size)+Math.max(width((q.after[focus.row]||'').slice(focus.start,focus.end),size),12)/2),350+(focus.row-start)*step];return {...q,count,changes,focus,visible,start,end,size,step,bottom,diag:bottom+54,bar:bottom+106,target};}
function background(){const g=ctx.createRadialGradient(540,850,30,540,850,1300);g.addColorStop(0,'#181e25');g.addColorStop(1,'#0e1217');ctx.fillStyle=g;ctx.fillRect(0,0,1080,1920);for(let x=120;x<=960;x+=60)for(let y=90;y<=1900;y+=60){ctx.fillStyle='#303942';ctx.fillRect(x,y,1,1);}for(const x of [80,1000])line([[x,80],[x,1900]],'#283039');for(const y of [80,1900]){line([[80,y],[110,y]],'#4c5862',2);line([[970,y],[1000,y]],'#4c5862',2);}tx('BUG ARCHIVE',120,109,23,M,true);line([[120,143],[960,143]],'#333e48');}
const keywords=new Set('void int float double string bool public private class return new if else null true false static var using'.split(' '));
function codeLine(s,x,baseline,size){font(size,true);ctx.textBaseline='alphabetic';ctx.textAlign='left';const re=/("(?:\\.|[^"\\])*"|\/\/.*|\b\d+(?:\.\d+)?\b|\b[A-Za-z_]\w*\b|.)/g;let m;while((m=re.exec(s))){let c=FG,t=m[0];if(t.startsWith('"'))c='#dcaf92';else if(t.startsWith('//'))c='#839582';else if(keywords.has(t))c='#c3a6e8';else if(/^\d/.test(t))c='#b6cca4';else if(['Debug','Console'].includes(t))c='#87d9e7';else if(/^[A-Za-z_]/.test(t)&&s.slice(re.lastIndex).trimStart().startsWith('('))c='#d9d4a9';ctx.fillStyle=c;ctx.fillText(t,x,baseline);x+=ctx.measureText(t).width;}}
function drawBug(x,y,height=80,gray=false,angle=0){ctx.save();ctx.translate(x,y);ctx.rotate(angle);if(gray)ctx.filter='grayscale(1)';const scale=height/bug.height;ctx.drawImage(bug,-bug.width*scale/2,-height/2,bug.width*scale,height);ctx.restore();}
function archive(t,forceLocked=false){const locked=forceLocked||t<=10.45;rr(160,570,760,780,26,'#1b242a',locked?'#78828a':L);for(const [x,y,sx,sy]of[[183,593,1,1],[897,593,-1,1],[183,1327,1,-1],[897,1327,-1,-1]])line([[x,y+22*sy],[x,y],[x+22*sx,y]],locked?M:L,3);tx(locked?'LOCKED':'UNLOCKED',540,637,27,locked?M:L,true,'center');circle(540,905,180,null,locked?'#3c4348':'#354337');circle(540,905,162,null,locked?'#30383f':'#29372f');if(!locked)glow(540,905,200);drawBug(540,905,260,locked,locked?0:Math.sin((t-10.45)*4)*.035);line([[215,1110],[865,1110]],'#333e48');tx(model.error_code,540,1184,78,FG,true,'center');message(model.message,540,1272,32,650,'center',locked?M:L);}
function draw(t=time,thumbnail=false){if(!ready||!model)return;ctx.clearRect(0,0,1080,1920);background();if(t>=10||thumbnail){archive(t,thumbnail);}else{const q=model,fix=t>=6;tx('Find the error in the code.',120,205,48);rr(120,266,840,q.bottom-266,18,'#1d242c','#3b4650');rr(120,266,840,60,18,'#252e37');ctx.fillStyle='#252e37';ctx.fillRect(121,306,838,20);tx(q.filename,150,296,25,M,true);tx('C#',930,296,23,M,true,'right');if(q.count>q.visible)tx(`L${q.start+1}–${q.end} / ${q.count}`,780,296,20,M,true,'right');line([[121,326],[959,326]],'#333e48');font(q.size,true);let metrics=ctx.measureText('0123456789Ag'),offset=(metrics.actualBoundingBoxAscent-metrics.actualBoundingBoxDescent)/2;const lines=fix?q.after:q.before;for(let row=q.start;row<Math.min(q.end,lines.length);row++){const y=350+(row-q.start)*q.step,b=y+offset,s=lines[row];if(fix)for(const ch of q.changes.filter(c=>c.row===row)){let x=220+width(s.slice(0,ch.start),q.size),w=Math.max(12,width(s.slice(ch.start,ch.end),q.size));rr(x-2,y-q.size*.62,w+4,q.size*1.24,6,'#354928');}font(q.size,true);ctx.fillStyle='#697987';ctx.textBaseline='alphabetic';ctx.textAlign='right';ctx.fillText(String(row+1),177,b);codeLine(s,220,b,q.size);if(fix)for(const ch of q.changes.filter(c=>c.row===row)){font(q.size,true);ctx.fillStyle=L;ctx.fillText(s.slice(ch.start,ch.end),220+width(s.slice(0,ch.start),q.size),b);}}if(!fix){const f=q.focus,a=q.before[f.row]||'',w=Math.max(24,width(a.slice(f.start,f.oldend),q.size));const x=Math.min(220+width(a.slice(0,f.start),q.size),920-w),y=q.target[1]+q.size*.6,pts=[];for(let k=0;k<=w;k+=6)pts.push([x+k,y+(Math.floor(k/6)%2?3:0)]);line(pts,R,2);}circle(128,q.diag,8,fix?'#52604d':R);tx(q.error_code,155,q.diag,29,fix?M:R,true);const div=155+width(q.error_code,29)+28;line([[div,q.diag-14],[div,q.diag+14]],'#333e48',2);message(q.message,div+28,q.diag,29,960-div-28,'left',fix?M:FG);rr(120,q.bar-3,756,6,3,'#35414d');rr(120,q.bar-3,Math.max(1,756*Math.min(t/6,1)),6,3,fix?L:'#96a6b7');if(t>=3&&t<6)tx(String(3-Math.floor(t-3)),932,q.bar,37,FG,true,'center');else if(fix)line([[917,q.bar-1],[927,q.bar+9],[947,q.bar-11]],L,3);
const pose=t<4?0:t<5?1:t<6?2:t<8.35?3:4;ctx.save();ctx.translate(660,1694+Math.sin(t*2.6)*3);if(t<6)ctx.rotate(2.5*Math.sin(t*2)*Math.PI/180);if(pose===3)ctx.scale(-1,1);ctx.drawImage(hosts[pose],-210,-210,420,420);ctx.restore();if(t>=3&&t<6)for(let j=0;j<3;j++)circle(390+j*19,1595,j>Math.floor(t*2%3)?3:5,M);if(t>=6&&t<7.9){const f=[781,1631],p=ease((t-6)/.32),a=f.map((v,i)=>v+(q.target[i]-v)*p);line([f,a],'#6f9241',2);circle(...a,5,L);}if(t>=7.5&&t<8.6){let p=ease((t-7.5)/1.1),a=bez(q.target,[340,Math.max(900,q.target[1]+60)],[275,1590],[552,1660],p);glow(...a,60);drawBug(...a,12+68*Math.min(1,(t-7.5)/.25),false,Math.sin(p*12)*.2);}else if(t>=8.6&&t<8.88){glow(552,1660);drawBug(552,1660,60);}else if(t>=8.88&&t<9.48){const p=ease((t-8.88)/.6),a=bez([552,1660],[580,1760],[780,1720],[698,1844],p);glow(...a);drawBug(...a,60*(1-p)+8);}if(t>=9.3&&t<10)glow(698,1844,95*(1-(t-9.3)/.7));}
if($('guides').checked&&!thumbnail){ctx.fillStyle='#00000065';ctx.fillRect(930,850,150,1070);ctx.fillRect(0,1720,1080,200);tx('UI OVERLAY',970,1190,19,'#ffffff88',true,'center');tx('CHANNEL / CAPTION',540,1790,25,'#ffffff88',true,'center');} }
function status(s,error=false){$('status').textContent=s;$('status').classList.toggle('error',error);}
function update(){try{model=build();draw();$('lineinfo').textContent=`${model.count} lines · ${model.visible} visible · ${model.size}px`;status(model.count>28?`Showing lines ${model.start+1}–${model.end} around the repair.`:'Ready.');try{localStorage.setItem('bugarchive-v2',JSON.stringify(cfg()));}catch{}}catch(e){status(e.message,true);model=null;}}
async function setConfig(q){for(const k of ['error_code','message','before','after'])if(!(k in q))throw Error(`Missing ${k}`);$('errorcode').value=q.error_code;$('filename').value=q.filename||'Player.cs';$('message').value=q.message;$('before').value=q.before.join('\n');$('after').value=q.after.join('\n');$('focus').value=q.focus_line||'';if(q.bug_data_url)await setBug(q.bug_data_url);else if(!q.bug||q.bug.includes('CS1002'))await setBug(STUDIO_ASSETS.CS1002);else status('Choose the bug PNG for this project.');update();}
async function setBug(src){const im=await loadImage(src),temp=document.createElement('canvas');temp.width=im.width;temp.height=im.height;const d=temp.getContext('2d');d.drawImage(im,0,0);const data=d.getImageData(0,0,im.width,im.height).data;let x0=im.width,y0=im.height,x1=-1,y1=-1,transparent=false;for(let y=0;y<im.height;y++)for(let x=0;x<im.width;x++){const a=data[(y*im.width+x)*4+3];if(a<255)transparent=true;if(a>0){x0=Math.min(x0,x);y0=Math.min(y0,y);x1=Math.max(x1,x);y1=Math.max(y1,y);}}if(!transparent)throw Error('Choose a PNG with a genuinely transparent background.');if(x1<0)throw Error('The PNG is empty.');let w=x1-x0+1,h=y1-y0+1;const out=document.createElement('canvas');out.width=w;out.height=Math.max(h,Math.ceil(w/1.5));out.getContext('2d').drawImage(im,x0,y0,w,h,0,(out.height-h)/2,w,h);bugData=out.toDataURL('image/png');bug=await loadImage(bugData);$('bugthumb').src=bugData;}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),10000);}
function save(){try{build();download(new Blob([JSON.stringify(cfg(),null,2)],{type:'application/json'}),`${cfg().error_code}.json`);status('Project saved with its bug image.');}catch(e){status(e.message,true);}}
$('save').onclick=save;$('offlineSave').onclick=save;$('closeDialog').onclick=()=>$('offline').close();$('open').onclick=()=>$('projectfile').click();$('projectfile').onchange=async e=>{try{if(e.target.files[0])await setConfig(JSON.parse(await e.target.files[0].text()));}catch(e){status(e.message,true);}};
$('choosebug').onclick=()=>$('bugfile').click();$('bugfile').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>8*1024*1024)throw Error('Use a PNG smaller than 8 MB.');const reader=new FileReader();reader.onload=async()=>{try{await setBug(reader.result);update();}catch(e){status(e.message,true);}};reader.readAsDataURL(f);}catch(e){status(e.message,true);}};
for(const id of ['before','after','errorcode','message','filename','focus'])$(id).oninput=update;
$('time').oninput=()=>{playing=false;$('play').textContent='Play';time=Number($('time').value);$('clock').textContent=`${time.toFixed(2)} / 12s`;draw();};$('guides').onchange=()=>draw();document.querySelectorAll('[data-time]').forEach(b=>b.onclick=()=>{$('time').value=b.dataset.time;$('time').oninput();});
$('play').onclick=()=>{playing=!playing;if(playing&&time>11.9)time=0;$('play').textContent=playing?'Pause':'Play';last=performance.now();};function loop(now){if(playing&&ready){time+=(now-last)/1000;if(time>=12){time=11.99;playing=false;$('play').textContent='Play';}$('time').value=time;$('clock').textContent=`${time.toFixed(2)} / 12s`;try{draw();}catch(e){playing=false;status(e.message,true);}}last=now;requestAnimationFrame(loop);}requestAnimationFrame(loop);
$('thumbnail').onclick=()=>{try{model=build();draw(10.4,true);C.toBlob(b=>download(b,`${model.error_code}-locked.png`),'image/png');draw();status('Gray LOCKED thumbnail saved.');}catch(e){status(e.message,true);}};
$('longexample').onclick=()=>setConfig(longExample()).catch(e=>status(e.message,true));function longExample(){const a=['using UnityEngine;','','public class Counter : MonoBehaviour','{','    private int score = 0;','    private int bonus = 5;','','    void Start()','    {','        score = 10;','        score += bonus;','        PrintScore();','    }','','    void PrintScore()','    {','        Debug.Log("Score")','        Debug.Log(score);','    }','','    void ResetScore()','    { score = 0; }','','}'];const b=[...a];b[16]+=';';return {...defaults,before:a,after:b,bug_data_url:bugData};}
$('render').onclick=async()=>{if(location.protocol==='file:'){$('offline').showModal();return;}if(activeJob)return;try{model=build();activeJob=true;$('render').disabled=true;status('Rendering MP4…');const r=await fetch('/api/render',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(cfg())});const result=await r.json();if(!r.ok)throw Error(result.error||'Render failed.');const poll=async()=>{try{const q=await fetch('/api/job/'+result.job),z=await q.json();if(z.status==='done'){status('MP4 and thumbnail are ready.');$('downloads').replaceChildren();for(const [name,url]of[['Download MP4',z.video],['Download thumbnail',z.thumbnail]]){const a=document.createElement('a');a.textContent=name;a.href=url;a.download='';$('downloads').append(a);}activeJob=false;$('render').disabled=false;}else if(z.status==='failed')throw Error(z.error||'Render failed.');else{status(z.progress||'Rendering MP4…');setTimeout(poll,1000);}}catch(e){activeJob=false;$('render').disabled=false;status(e.message,true);}};poll();}catch(e){activeJob=false;$('render').disabled=false;status(e.message,true);}};
async function init(){try{await Promise.all([new FontFace('ArchiveMono',`url(${STUDIO_ASSETS.DejaVuSansMono})`).load(),new FontFace('ArchiveSans',`url(${STUDIO_ASSETS.DejaVuSans})`).load()].map(async p=>document.fonts.add(await p)));hosts=await Promise.all([0,1,2,3,4].map(i=>loadImage(STUDIO_ASSETS['host-'+i])));await setBug(STUDIO_ASSETS.CS1002);ready=true;let q=defaults;try{const saved=localStorage.getItem('bugarchive-v2');if(saved)q=JSON.parse(saved);}catch{}await setConfig(q);$('mode').textContent=location.protocol==='file:'?'OFFLINE EDITOR':'LOCAL RENDER STUDIO';if(document.modelContext?.registerTool)document.modelContext.registerTool({name:'inspect_episode',description:'Read the current episode and preview layout.',inputSchema:{type:'object',properties:{}},annotations:{readOnlyHint:true},execute:()=>({error_code:model?.error_code,lines:model?.count,visible:model?.visible,time})});}catch(e){status(e.message,true);}}init();
